// Writes src/toolDates.generated.ts with when each tool was added and last
// updated, taken from the history of each tool's own repo. Runs before
// `npm run dev` and `npm run build`.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseGitLog, toolDatesFromCommits, type ToolDates } from '../src/gitHistory.ts';
import { repoLog, syncToolRepos } from './toolRepos.ts';

const outputPath = fileURLToPath(new URL('../src/toolDates.generated.ts', import.meta.url));

const dates: Record<string, ToolDates> = {};
for (const { tool, dir } of await syncToolRepos()) {
  const toolDates = toolDatesFromCommits(parseGitLog(await repoLog(dir)));
  if (toolDates) dates[tool.name] = toolDates;
}
const sorted = Object.fromEntries(Object.entries(dates).sort(([a], [b]) => a.localeCompare(b)));

writeFileSync(
  outputPath,
  [
    '// Generated by scripts/generate-tool-dates.ts from each tool repo. Do not edit.',
    "import type { ToolDates } from './gitHistory';",
    '',
    `export const TOOL_DATES: Record<string, ToolDates> = ${JSON.stringify(sorted, null, 2)};`,
    '',
  ].join('\n'),
);

console.log(`Wrote dates for ${Object.keys(sorted).length} tools.`);
