// Writes src/toolDates.generated.ts with when each tool was added and last
// updated, taken from git history. Runs before `npm run dev` and `npm run build`.

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { toolDatesFromGitLog } from '../src/gitHistory.ts';

const repoRoot = fileURLToPath(new URL('../..', import.meta.url));
const outputPath = fileURLToPath(new URL('../src/toolDates.generated.ts', import.meta.url));

function git(...args: string[]): string {
  return execFileSync(
    'git',
    ['-C', repoRoot, '-c', 'core.quotePath=false', '-c', 'diff.renameLimit=100000', ...args],
    { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 },
  );
}

if (git('rev-parse', '--is-shallow-repository').trim() === 'true') {
  // A shallow clone would date every tool to the newest commit.
  throw new Error('Tool dates need the full git history. Check out with fetch-depth: 0.');
}

const log = git('log', '--topo-order', '--reverse', '-M', '--name-status', '--format=%x00%cI');
const files = git('ls-files', '--', 'tools').split('\n').filter(Boolean);
const dates = toolDatesFromGitLog(log, files);
const sorted = Object.fromEntries(Object.entries(dates).sort(([a], [b]) => a.localeCompare(b)));

writeFileSync(
  outputPath,
  [
    '// Generated by scripts/generate-tool-dates.ts from git history. Do not edit.',
    "import type { ToolDates } from './gitHistory';",
    '',
    `export const TOOL_DATES: Record<string, ToolDates> = ${JSON.stringify(sorted, null, 2)};`,
    '',
  ].join('\n'),
);

console.log(`Wrote dates for ${Object.keys(sorted).length} tools.`);
